# Generated by Django 2.2 on 2021-05-05 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('number_of_lectures', models.IntegerField()),
            ],
        ),
    ]
